// -----------------------------------------
// 2021 US Open Player Pool
// found here: https://www.usopen.com/bin/usopen/players.json
// -----------------------------------------

export const fetchPlayerList = async () => {
  const playerRes = await fetch(
    'https://www.usopen.com/bin/usopen/players.json'
  ).then((res) => res.json());
  const players = playerRes.map((p) => {
    return `${p.firstName} ${p.lastName}`;
  });
  console.log('LOG: playerRes', JSON.stringify(players));
};

const players = [
  'Brooks Koepka',
  'Dustin Johnson',
  'Rory McIlroy',
  'Justin Thomas',
  'Collin Morikawa',
  'Patrick Cantlay',
  'Bryson DeChambeau',
  'Jordan Spieth',
  'Hideki Matsuyama',
  'Xander Schauffele',
  'Thomas Aiken',
  'Steve Allan',
  'Abraham Ancer',
  'Marcus Armitage',
  'Yosuke Asaji',
  'Chris Baker',
  'Luis Fernando Barco',
  'Paul Barjon',
  'Daniel Berger',
  'Christiaan  Bezuidenhout',
  'Akshay Bhatia',
  'Richard Bland',
  'Hayden Buckley',
  'Sam Burns',
  'Rafael  Cabrera Bello',
  'Mario Carmona',
  'Paul Casey',
  'Cameron Champ',
  'Stewart Cink',
  'Wyndham Clark',
  'Eric Cole',
  'Corey Conners',
  'Pierceson Coody',
  'Roy Cootes',
  'Dave Coupland',
  'Christopher Crawford',
  'Thomas Detry',
  'Harris  English',
  'Tony Finau',
  'Matthew Fitzpatrick',
  'Tommy Fleetwood',
  'Dylan Frittelli',
  'Wilson Furr',
  'Luis Gagne',
  'Sergio  Garcia',
  'Fabian Gomez',
  'Branden Grace',
  'Lanto Griffin',
  'Adam Hadwin',
  'Cole Hammer',
  'Brian Harman',
  'Tyrrell Hatton',
  'Russell Henley',
  'James Hervol',
  'Garrick Higgo',
  'Joe Highsmith',
  'Bo Hoag',
  'Charley Hoffman',
  'Tom Hoge',
  'Max Homa',
  'Billy Horschel',
  'Rikuya Hoshino',
  'Viktor Hovland',
  'Mackenzie Hughes',
  'John Huh',
  'Sungjae Im',
  'Ryo Ishikawa',
  'Zach Johnson',
  'Michael Johnson',
  'Matt Jones',
  'Sunghoon Kang',
  'Martin Kaymer',
  'Brad Kennedy',
  'Si Woo Kim',
  'Chan Kim',
  'Kevin Kisner',
  'Jason Kokrak',
  'Andrew Kozan',
  'Matt Kuchar',
  'Martin Laird',
  'Rick Lamb',
  'Kyoung-Hoon Lee',
  'Marc Leishman',
  'Joe Long',
  'Shane Lowry',
  'Robert MacIntyre',
  'Peter Malnati',
  'Adrian Meronk',
  'Troy Merritt',
  'Dylan Meyer',
  'Phil Mickelson',
  'Guido Migliozzi',
  'Francesco Molinari',
  'Edoardo Molinari',
  'Taylor Montgomery',
  'Sebastian Munoz',
  'Kevin Na',
  'Joaquin Niemann',
  'Wilco Nienaber',
  'Louis Oosthuizen',
  'Wade Ormsby',
  'Carlos Ortiz',
  'Alvaro Ortiz',
  'Charles Osborne',
  'Ryan Palmer',
  'Taylor Pendrith',
  'Victor Perez',
  'Andy  Pope',
  'J.T. Poston',
  'Ian Poulter',
  'Jon Rahm',
  'Spencer Ralston',
  'Chez Reavie',
  'Patrick Reed',
  'Patrick Rodgers',
  'Justin Rose',
  'Sam Ryder',
  'Carson Schaake',
  'Scottie Scheffler',
  'Matthias Schmid',
  'Charl Schwartzel',
  'Adam Scott',
  'Matthew Sharpstene',
  'Robby Shelton',
  'Davis Shore',
  'Greyson Sigg',
  'Webb Simpson',
  'Cameron Smith',
  'Jordan Smith',
  'Matthew Southgate',
  'J.J. Spaun',
  'Hayden Springer',
  'Brendan Steele',
  'Henrik Stenson',
  'Tyler Strafaci',
  'Kevin Streelman',
  'Brian Stuard',
  'Justin Suh',
  'Sahith Theegala',
  'Brendon Todd',
  'Erik Van Rooyen',
  'Johannes Veerman',
  'Jhonattan Vegas',
  'Jimmy Walker',
  'Matt Wallace',
  'Bubba Watson',
  'Kyle Westmoreland',
  'Lee Westwood',
  'Bernd Wiesberger',
  'Matthew Wolff',
  'Gary Woodland',
  'Dylan Wu',
  'Cameron Young',
  'Zach Zaback',
  'Will Zalatoris',
];

export default players;
